version: '3.9'

services:
  bot.api:
    image: ${DOCKER_REGISTRY-}botapi
    build:
      context: .
      dockerfile: Bot.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5024:80"
    networks:
      - app-chat

  chat.ui:
    image: ${DOCKER_REGISTRY-}chatui
    build:
      context: .
      dockerfile: Chat.UI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5039:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - app-chat

  producer.api:
    image: ${DOCKER_REGISTRY-}producerapi
    build:
      context: .
      dockerfile: Producer.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5212:80"
    networks:
      - app-chat

networks:
  app-chat:
    driver: bridge
