version: '3.9'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=Password*123456
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - app-chat
    container_name: sqlServer-chat-web
    volumes:
      - sqlserver-data:/var/opt/sqlserver/data
      - sqlserver-log:/var/opt/sqlserver/log
      - sqlserver-backup:/var/opt/sqlserver/backup

  rabbitmq:
    image: rabbitmq:3.9.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-chat
    container_name: rabbit-chat-web
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  sqlserver-data:
  sqlserver-log:
  sqlserver-backup:
  rabbitmq-data:

networks:
  app-chat:
